name: Run Tox tests

permissions:
  contents: read

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Python ${{ matrix.python-version }}, Postgres=${{ matrix.with-postgres }}"

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        with-postgres: [true, false]
      fail-fast: false

    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        fetch-depth: 0 # fetch all history including tags -- necessary to determine the version from SCM
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Install PostgreSQL
      if: ${{ matrix.with-postgres }}
      uses: tj-actions/install-postgresql@a889ed6c6fa05022333ed4101295bb1d604f97a8 # v3.2.0
      with:
        postgresql-version: 17
    - name: Tox flake8
      run: tox -e flake8
    - name: Tox docs
      run: tox -e docs
    - name: Tox mypy
      run: tox -e mypy
    - name: Tox py3
      run: tox -e py3
